import React from 'react';
import { Link, useLocation } from 'react-router-dom';
import radar from '../assets/radar.png'

const Overview = () => {
  return (
  <main className="flex-1 pt-16">
    <div className="w-screen h-screen flex items-center justify-center over_bg bg-gray-800 text-white">
      <div className="container mx-20 mt-20 px-10 pb-1 mb-12">
        <div className="lg:w-1/2">
          <div className='text-conent mb-10'>
            <h1 className="text-5xl font-bold mb-5 text-white">Precision in the Sky,</h1>
            <h1 className="text-5xl font-bold mb-12 text-white">Clarity on the Ground.</h1>
            <p className="text-lg mb-6 text-justify text-white">
              Welcome to the overview of our cutting-edge Micro-Doppler Based Target Classification system. This innovative project leverages advanced radar sensor technology and machine learning algorithms to differentiate between various types of objects, such as drones and birds, based on their unique micro-Doppler signatures.
            </p>
            <p className="text-lg mb-6 text-justify text-white">
              The system uses micro-Doppler signatures captured from radar sensors to identify and classify targets. This is achieved through the analysis of distinctive features generated by rotating blades of drones and the wing beats of birds. Our solution provides accurate and real-time classification, making it highly valuable for applications in security and surveillance.
            </p>
            <div className="mt-6 flex flex-wrap">
              <Link to="/Signup">
                <button className="bg-gray-800 text-orange-600 hover:text-orange-600 py-3 px-6 font-medium rounded-full m-2 hover:bg-white">
                    Signup
                </button>
              </Link>
              <Link to="/Login">
                  <button className="bg-orange-600 text-white hover:text-orange-600 py-3 px-6 font-medium rounded-full m-2 hover:bg-white">
                      Login
                  </button>
              </Link>
            </div>
          </div>
        </div>
        {/* <div className="image-container mx-20  flex items-center justify-center">
          <img src={radar} alt=""/>
        </div> */}
      </div>
    </div>
  </main>
  );
};

export default Overview;